spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/daydayup_2?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driverClassName: com.mysql.cj.jdbc.Driver
